# [![Build Status](https://travis-ci.org/dex4er/perl-Plack-Middleware-TrafficLog.png?branch=master)](https://travis-ci.org/dex4er/perl-Plack-Middleware-TrafficLog)

language: perl
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq spell
  - cpanm --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton
  - cpanm --with-recommends --installdeps --notest --skip-satisfied .
script: ./Dist.SH
perl:
  - 5.18
  - 5.8
